# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 736da0c30635bc1c0934165f3ffca395e6de0ea53f4d61a2532c4f1cc13f4efc9e3c65d5712cfa4bf0efae6a87fd93a91c371f34344d8c9e06438163462c1c2e

test:
  secret_key_base: c5639df8e299c59b5d5c07229ad5d42d52f3c70109ae7f2c5e8cc76e1428d7e875e6deb561003648bdd1089458a72dec063af6990f8b0d509e7d31222d0ea376

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
